/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controlers.PrimaryController;
import datamodel.interfaces.IExperimentModel;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * The applications main form
 *
 * @author rtucker
 */
public class CardsMainForm extends BaseCardWindow {

    /**
     * Creates new form CardsMainForm
     */
    public CardsMainForm() {
        initComponents();
        ViewUtils.centreFrame(this);
        initialise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrMainViewPane = new javax.swing.JScrollPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuEdit = new javax.swing.JMenu();
        mnuTrialSettings = new javax.swing.JMenuItem();
        mnuParticipant = new javax.swing.JMenuItem();
        mnuBeginTrial = new javax.swing.JMenuItem();
        mnuCompleteExperiment = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCreateDecks = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrMainViewPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mnuEdit.setText("Edit");

        mnuTrialSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnuTrialSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear--pencil.png"))); // NOI18N
        mnuTrialSettings.setText("Setup Trial");
        mnuTrialSettings.setToolTipText("Define trial parameters");
        mnuTrialSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrialSettingsActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuTrialSettings);

        mnuParticipant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuParticipant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Person.png"))); // NOI18N
        mnuParticipant.setText("Edit participant details");
        mnuParticipant.setToolTipText("Enter or change participant information");
        mnuParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuParticipantActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuParticipant);

        mnuBeginTrial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBeginTrial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card--plus.png"))); // NOI18N
        mnuBeginTrial.setText("Start Experiment");
        mnuBeginTrial.setToolTipText("Begin a new trial");
        mnuBeginTrial.setEnabled(false);
        mnuBeginTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBeginTrialActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuBeginTrial);

        mnuCompleteExperiment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        mnuCompleteExperiment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick-circle-frame.png"))); // NOI18N
        mnuCompleteExperiment.setText("Complete Experiment");
        mnuCompleteExperiment.setToolTipText("Confirm your choices and save results");
        mnuCompleteExperiment.setEnabled(false);
        mnuCompleteExperiment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCompleteExperimentActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuCompleteExperiment);
        mnuEdit.add(jSeparator1);

        mnuCreateDecks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuCreateDecks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card--plus.png"))); // NOI18N
        mnuCreateDecks.setText("Create Card Decks");
        mnuCreateDecks.setToolTipText("Tool to generate pre-defined card decks");
        mnuCreateDecks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreateDecksActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuCreateDecks);

        mnuBar.add(mnuEdit);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMainViewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMainViewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTrialSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrialSettingsActionPerformed
        showTrialSettings();
    }//GEN-LAST:event_mnuTrialSettingsActionPerformed

    private void mnuParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuParticipantActionPerformed
        ParticipantEntryWindow2 window = new ParticipantEntryWindow2();
        window.setController(controller);
        ViewUtils.centreFrame(window);
        window.setVisible(true);
    }//GEN-LAST:event_mnuParticipantActionPerformed

    private void mnuBeginTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBeginTrialActionPerformed
        this.controller.startExperiment();
    }//GEN-LAST:event_mnuBeginTrialActionPerformed

    private void mnuCreateDecksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreateDecksActionPerformed
        DeckCreationDialog createDialog = new DeckCreationDialog(this, true);
        createDialog.setController(controller);
        ViewUtils.centreDialog(createDialog);
        createDialog.setVisible(true);
    }//GEN-LAST:event_mnuCreateDecksActionPerformed

    private void mnuCompleteExperimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCompleteExperimentActionPerformed
        try {
            this.controller.endExperiment();
        } catch (IllegalStateException ex) {
            Logger.getLogger(CardsMainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Experiment in illegal state to complete...", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(CardsMainForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error saving to file...", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnuCompleteExperimentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CardsMainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuBeginTrial;
    private javax.swing.JMenuItem mnuCompleteExperiment;
    private javax.swing.JMenuItem mnuCreateDecks;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuParticipant;
    private javax.swing.JMenuItem mnuTrialSettings;
    private javax.swing.JScrollPane scrMainViewPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        configureMenus();
    }

    public void setView(JPanel aPanel) {
        if (null != aPanel) {
            scrMainViewPane.setViewportView(aPanel);
        } else {
            JPanel blank = new JPanel();
            scrMainViewPane.setViewportView(blank);
        }
    }

    public void showInvalidParticipantWarning() {
        JOptionPane.showMessageDialog(this, "Participant details are invalid. Please enter valid details.", "Error cannot start experiment...", JOptionPane.ERROR_MESSAGE);
        this.mnuParticipantActionPerformed(null);
    }

    private void showTrialSettings() {
        try {
            TrialSetupDialog settingsWin = new TrialSetupDialog(this, true);
            settingsWin.setModal(true);
            settingsWin.setController(controller);
            ViewUtils.centreDialog(settingsWin);
            settingsWin.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error message is: " + ex.getMessage(), "Error cannot access experiment settings...", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initialise() {
        this.controller = new PrimaryController(this);
        IExperimentModel myExperiment;
        myExperiment = this.controller.getExpModel();
        myExperiment.registerObserver(this);
        myExperiment.notifyObservers();
    }

    private void configureMenus() {
        if (this.controller.isExperimentRunning()) {
            //Disable Participant entry, Equipment setup & Start Experiment
            mnuBeginTrial.setEnabled(false);
            mnuParticipant.setEnabled(false);
            mnuTrialSettings.setEnabled(false);
            //Enable complete experiment
            mnuCompleteExperiment.setEnabled(true);
        } else {
            //Enable Participant entry, Experiment setup & Start Experiment
            int noOfDecks = this.controller.getExpModel().getNoOfDecks();
            boolean hasValidParticipant = this.controller.getExpModel().hasValidParticipant();
            if (0 < noOfDecks && hasValidParticipant) {
                mnuBeginTrial.setEnabled(true);
            } else {
                mnuBeginTrial.setEnabled(false);
            }
            mnuParticipant.setEnabled(true);
            mnuTrialSettings.setEnabled(true);
            //Disable complete experiment
            mnuCompleteExperiment.setEnabled(false);
        }
    }
}
