/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controlers.PrimaryController;
import datamodel.interfaces.IExperimentModel;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 * The applications main form
 * @author rtucker
 */
public class CardsMainForm extends BaseCardWindow {
    
    private IExperimentModel myExperiment;

    /**
     * Creates new form CardsMainForm
     */
    public CardsMainForm() {
        initComponents();
        ViewUtils.centreFrame(this);
        initialise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrMainViewPane = new javax.swing.JScrollPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemSaveTrialData = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuTrialSettings = new javax.swing.JMenuItem();
        mnuParticipant = new javax.swing.JMenuItem();
        mnuBeginTrial = new javax.swing.JMenuItem();
        mnuCompleteExperiment = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrMainViewPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mnuFile.setText("File");

        mnuItemSaveTrialData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemSaveTrialData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disk-return-black.png"))); // NOI18N
        mnuItemSaveTrialData.setText("Save Trial Data");
        mnuItemSaveTrialData.setToolTipText("Save previous trial data");
        mnuItemSaveTrialData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSaveTrialDataActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemSaveTrialData);

        mnuBar.add(mnuFile);

        mnuEdit.setText("Edit");

        mnuTrialSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnuTrialSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear--pencil.png"))); // NOI18N
        mnuTrialSettings.setText("Setup Trial");
        mnuTrialSettings.setToolTipText("Define trial parameters");
        mnuTrialSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrialSettingsActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuTrialSettings);

        mnuParticipant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuParticipant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Person.png"))); // NOI18N
        mnuParticipant.setText("Edit participant details");
        mnuParticipant.setToolTipText("Enter or change participant information");
        mnuParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuParticipantActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuParticipant);

        mnuBeginTrial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBeginTrial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card--plus.png"))); // NOI18N
        mnuBeginTrial.setText("Start Experiment");
        mnuBeginTrial.setToolTipText("Begin a new trial");
        mnuBeginTrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBeginTrialActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuBeginTrial);

        mnuCompleteExperiment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        mnuCompleteExperiment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick-circle-frame.png"))); // NOI18N
        mnuCompleteExperiment.setText("Complete Experiment");
        mnuCompleteExperiment.setToolTipText("Confirm your choices and save results");
        mnuEdit.add(mnuCompleteExperiment);

        mnuBar.add(mnuEdit);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMainViewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMainViewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemSaveTrialDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSaveTrialDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemSaveTrialDataActionPerformed

    private void mnuTrialSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrialSettingsActionPerformed
        showTrialSettings();
    }//GEN-LAST:event_mnuTrialSettingsActionPerformed

    private void mnuParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuParticipantActionPerformed
        ParticipantEntryWindow window = new ParticipantEntryWindow();
        window.setController(controller);
        window.setVisible(true);
    }//GEN-LAST:event_mnuParticipantActionPerformed

    private void mnuBeginTrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBeginTrialActionPerformed
        this.controller.startExperiment();
    }//GEN-LAST:event_mnuBeginTrialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CardsMainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuBeginTrial;
    private javax.swing.JMenuItem mnuCompleteExperiment;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuItemSaveTrialData;
    private javax.swing.JMenuItem mnuParticipant;
    private javax.swing.JMenuItem mnuTrialSettings;
    private javax.swing.JScrollPane scrMainViewPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        configureMenus();
    }
    
    public void setView(JPanel aPanel){
        if(null != aPanel){
            scrMainViewPane.setViewportView(aPanel);
        }else{
            JPanel blank = new JPanel();
            scrMainViewPane.setViewportView(blank);
        }
    }
    
    private void showTrialSettings() {
        JDialog settingsWin = new TrialSetupDialog(this, true);
        settingsWin.setModal(true);
        ViewUtils.centreDialog(settingsWin);
        settingsWin.setVisible(true);
    }

    private void initialise() {
        this.controller = new PrimaryController(this);
        this.myExperiment = this.controller.getExpModel();
        this.myExperiment.registerObserver(this);
        this.myExperiment.notifyObservers();
    }

    private void configureMenus() {
        if(this.controller.isExperimentRunning()){
            //Disable Participant entry, Equipment setup & Start Experiment
            mnuBeginTrial.setEnabled(false);
            mnuParticipant.setEnabled(false);
            mnuTrialSettings.setEnabled(false);
            //Enable complete experiment
            mnuCompleteExperiment.setEnabled(true);
        } else {
            //Enable Participant entry, Experiment setup & Start Experiment
            mnuBeginTrial.setEnabled(true);
            mnuParticipant.setEnabled(true);
            mnuTrialSettings.setEnabled(true);
            //Disable complete experiment
            mnuCompleteExperiment.setEnabled(false);
        }
    }
}
