/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controlers.PrimaryController;
import datamodel.interfaces.IControllable;
import datamodel.interfaces.IController;
import datamodel.interfaces.IExperimentModel;
import javax.swing.JDialog;

/**
 *
 * @author rtucker
 */
public class CardsMainForm extends javax.swing.JFrame implements IControllable {
    
    private IExperimentModel myExperiment;
    private IController controller;

    /**
     * Creates new form CardsMainForm
     */
    public CardsMainForm() {
        initComponents();
        ViewUtils.centreFrame(this);
        initialise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrMainViewPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemSaveTrialData = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuTrialSettings = new javax.swing.JMenuItem();
        mnuParticipant = new javax.swing.JMenuItem();
        mnuBeginTrial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrMainViewPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("File");

        mnuItemSaveTrialData.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemSaveTrialData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disk-return-black.png"))); // NOI18N
        mnuItemSaveTrialData.setText("Save Trial Data");
        mnuItemSaveTrialData.setToolTipText("Save previous trial data");
        mnuItemSaveTrialData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSaveTrialDataActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemSaveTrialData);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mnuTrialSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnuTrialSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear--pencil.png"))); // NOI18N
        mnuTrialSettings.setText("Setup Trial");
        mnuTrialSettings.setToolTipText("Define trial parameters");
        mnuTrialSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrialSettingsActionPerformed(evt);
            }
        });
        jMenu2.add(mnuTrialSettings);

        mnuParticipant.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuParticipant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Person.png"))); // NOI18N
        mnuParticipant.setText("Edit participant details");
        mnuParticipant.setToolTipText("Enter or change participant information");
        mnuParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuParticipantActionPerformed(evt);
            }
        });
        jMenu2.add(mnuParticipant);

        mnuBeginTrial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBeginTrial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playing-card--plus.png"))); // NOI18N
        mnuBeginTrial.setText("Start Experiment");
        mnuBeginTrial.setToolTipText("Begin a new trial");
        jMenu2.add(mnuBeginTrial);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMainViewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrMainViewPane, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemSaveTrialDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSaveTrialDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemSaveTrialDataActionPerformed

    private void mnuTrialSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrialSettingsActionPerformed
        // TODO add your handling code here:
        showTrialSettings();
    }//GEN-LAST:event_mnuTrialSettingsActionPerformed

    private void mnuParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuParticipantActionPerformed
        ParticipantEntryWindow window = new ParticipantEntryWindow();
        window.setController(controller);
        window.setVisible(true);
    }//GEN-LAST:event_mnuParticipantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardsMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuBeginTrial;
    private javax.swing.JMenuItem mnuItemSaveTrialData;
    private javax.swing.JMenuItem mnuParticipant;
    private javax.swing.JMenuItem mnuTrialSettings;
    private javax.swing.JScrollPane scrMainViewPane;
    // End of variables declaration//GEN-END:variables

    private void showTrialSettings() {
        JDialog settingsWin = new TrialSetupDialog(this, true);
        settingsWin.setModal(true);
        ViewUtils.centreDialog(settingsWin);
        settingsWin.setVisible(true);
    }

//<editor-fold defaultstate="collapsed" desc="IControllable implementation">
    @Override
    public IController getController() {
        return this.controller;
    }
    
    @Override
    public boolean setController(IController aController) {
        boolean result = false;
        if(null != aController){
            this.controller = aController;
        }
        return result;
    }
//</editor-fold>

    private void initialise() {
        this.controller = new PrimaryController();
    }
}
