/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import datamodel.exceptions.IncompleteExperimentDefinitionException;
import datamodel.interfaces.IExperimentGenerator;
import datamodel.interfaces.IExperimentModel;

/**
 * Using this JPanel a user can setup manually the experiments parameters
 * @author rtucker
 */
public class ManuallyDefineExperiment extends javax.swing.JPanel implements IExperimentGenerator {

    /**
     * Creates new form ManuallyDefineExperiment
     */
    public ManuallyDefineExperiment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDecks = new javax.swing.JTable();
        pnlDeckControls = new javax.swing.JPanel();
        btnAddDeck = new javax.swing.JButton();
        btnRemoveDeck = new javax.swing.JButton();

        tblDecks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Deck 1", "Infinite / Fixed", "FaceCard after X goes", "Path to XML for Fixed file type"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Deck Name", "Deck Type", "Max time between face cards", "File Path"
            }
        ));
        jScrollPane1.setViewportView(tblDecks);

        pnlDeckControls.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAddDeck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus-circle.png"))); // NOI18N
        btnAddDeck.setText("Add Deck");

        btnRemoveDeck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus-circle.png"))); // NOI18N
        btnRemoveDeck.setText("Remove Deck");

        javax.swing.GroupLayout pnlDeckControlsLayout = new javax.swing.GroupLayout(pnlDeckControls);
        pnlDeckControls.setLayout(pnlDeckControlsLayout);
        pnlDeckControlsLayout.setHorizontalGroup(
            pnlDeckControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeckControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddDeck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemoveDeck)
                .addContainerGap())
        );
        pnlDeckControlsLayout.setVerticalGroup(
            pnlDeckControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeckControlsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDeckControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDeck)
                    .addComponent(btnRemoveDeck))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addComponent(pnlDeckControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDeckControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDeck;
    private javax.swing.JButton btnRemoveDeck;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDeckControls;
    private javax.swing.JTable tblDecks;
    // End of variables declaration//GEN-END:variables

    @Override
    public IExperimentModel createExperimentModel() throws IncompleteExperimentDefinitionException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
