/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.components;

import com.gmail.qkitty6.patterns.observer.IObserver;
import datamodel.interfaces.IDeck;
import datamodel.interfaces.IDeckManager;
import java.util.ArrayList;
import javax.swing.JScrollBar;

/**
 *
 * @author qkitt
 */
public class DrawnCardsHistoryDisplayPanel extends javax.swing.JPanel implements IObserver<Void>, IDeckManager {

    private IDeck myCardDeck;

    /**
     * Creates new form DrawnCardsHistoryDisplayPanel
     *
     * @param aDeck - IDeck interface to the card deck that will provide data to
     * the panel
     */
    public DrawnCardsHistoryDisplayPanel(IDeck aDeck) {
        initComponents();
        this.setCardDeck(aDeck);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cardListPanel = new views.components.CardListPanel();

        jScrollPane1.setViewportView(cardListPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.components.CardListPanel cardListPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public IDeck getCardDeck() {
        return this.myCardDeck;
    }

    @Override
    public final void setCardDeck(IDeck aDeck) {
        if (null != aDeck) {
            if (null != this.myCardDeck) {
                this.myCardDeck.removeObserver(this);
            }
            this.myCardDeck = aDeck;
            this.myCardDeck.registerObserver(this);
            this.update();
        }
    }

    @Override
    public void update() {
        if (null != this.myCardDeck) {
            cardListPanel.replaceList(this.myCardDeck.getDrawnCardList());
        } else {
            cardListPanel.replaceList(new ArrayList<>());
        }
        //Put the horizontal scroll bar as far to the right as possible
        java.awt.EventQueue.invokeLater(() -> {
            JScrollBar hsb = jScrollPane1.getHorizontalScrollBar();
            hsb.setValue(hsb.getMaximum());
        });
    }
}
